### ISSUE TITLE
Unable to filter on List of Strings

### ISSUE THREAD

**Issue by rmorrise** [turkraft/springfilter#326]
Hi,

I am having trouble filtering on a ```List<String>``` field on my domain object. Any help would be appreciated!

The field is mapped as follows:

```
    @ElementCollection
    @CollectionTable(name = 'KNOWLEDGE_RECORD_DELIVERY_METHODS',
            joinColumns = @JoinColumn(name = 'KNOWLEDGE_RECORD_ID'))
    @Column(name = 'DELIVERY_METHOD_NAMES')
    @Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED,
            withModifiedFlag = true, modifiedColumnName = 'DELIVERY_METHODS_MOD')
    List<String> deliveryMethodList = []
```

When I use this filter: ```deliveryMethodList:'Complete'``` I get an exception (see below).

I also tried ```deliveryMethod in ['Complete']``` but I couldn't get this to work, either... parsing fails on the first square bracket.

```
com.turkraft.springfilter.exception.InternalFilterException: The input 'Complete' could not be converted to interface java.util.List
	at com.turkraft.springfilter.parser.generator.expression.ExpressionGenerator.visitInput(ExpressionGenerator.java:482)
	at com.turkraft.springfilter.parser.generator.expression.ExpressionGenerator.visitInput(ExpressionGenerator.java:44)
	at com.turkraft.springfilter.parser.FilterParser$InputContext.accept(FilterParser.java:158)
	at com.turkraft.springfilter.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.turkraft.springfilter.parser.generator.expression.ExpressionGenerator.visitComparison(ExpressionGenerator.java:200)
... (edited for brevity)
	at com.turkraft.springfilter.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.turkraft.springfilter.parser.generator.expression.ExpressionGenerator.run(ExpressionGenerator.java:53)
	at com.turkraft.springfilter.boot.FilterSpecification.toPredicate(FilterSpecification.java:57)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.applySpecificationToCriteria(SimpleJpaRepository.java:879)
```

Looking at the bytecode, I can't see any obvious way to work around this.

I am using ```com.turkraft:spring-filter:2.1.1```

Thanks

**Comment by torshid** [comment]
Hey @rmorrise,

If you're using version 2.x, you may try the query `deliveryMethod in ('Complete')` (square brackets are used in 3.x). Note that I am not actively maintaining that version anymore, you should update to 3.x.

**Comment by rmorrise** [comment]
@torshid Thanks for the prompt reply!
I tried the ```( )``` syntax but it still gives the same error:

```
The input 'Complete' could not be converted to interface java.util.List
```

I will try upgrading to 3.x and see if this fixes the issue.
